const strings = {
  more: 'Read more',
  less: 'Show less',
  tabs: {
    course: 'Courses',
    program: 'Program',
    session: 'Sessions',
    workshop: 'Workshop',
    resource: 'Resources',
  },
  email: {
    sent: 'Email has been sent!',
    message: 'Please check your inbox to reset password',
    receive: "Didn't receive the email?",
    resend: 'Resend',
  },
  forgot: {
    password: 'Forgot your password?',
    message: 'Please enter your email address to reset your password',
  },
  welcome: {
    hi: 'Welcome',
    start: 'Get Started',
  },
  signin: {
    google: 'Continue with Google',
    apple: 'Continue With Apple',
    logIn: 'Login',
    send: 'Send',
    action: 'Sign In',
    email: 'Email',
    password: 'Password',
    registerMessage: " Don't have an account?",
    registerLink: ' Create one',
  },
  register: {
    next: 'Continue',
    agreeDesc: 'By continuing you agree to our ',
    agreeTC: 'Terms of Use',
    agreeAnd: 'and',
    agreePrivacy: 'Privacy Policy',
    switchAccount: 'Switch account',
    customer: {
      title: 'Your details',
      firstName: 'First Name*',
      lastName: 'Last Name*',
      email: 'Email*',
      phone: 'Phone Number',
      password: 'Password*',
      passwordRules: 'Your password must:',
      passwordChar: 'Be at least 8 characters',
      passwordLower: 'Include a lowercase letter',
      passwordNumber: 'Include a number',
      accountError: 'This account already exists',
      action: 'Create Account',
    },
    member: {
      title: 'Your child details',
      firstName: 'First Name*',
      lastName: 'Last Name*',
      gender: 'Gender*',
      action: 'Continue',
    },
    thankYou: {
      allDone: (firstName: string) => `All done, ${firstName}!`,
      resetPassword: (firstName: string) => `Thanks ${firstName || ''}. Please check your email inbox to reset your password.`,
      loginButton: 'Sign in',
      startButton: "Let's explore",
    },
    customerAvatar: {
      title: 'Take a snapshot',
      permissionTitle: 'Cool Photo App Camera Permission',
      permissionMessage:
        'Cool Photo App needs access to your camera '
        + 'so you can take awesome pictures.',
      permissionNeuturalButton: 'Ask Me Later',
      permissionNegativeButton: 'Cancel',
      permissionPositiveButton: 'Ok',
      usePhotoLibrary: 'Use Photo Library',
      useCamera: 'Use Camera',
      pickPhoto: 'Pick Your Photo',
      cancel: 'Cancel',
      continue: 'Continue',
      skip: 'Skip this for later',
    },
  },
  usersignup: {},
  coursecard: {
    download: 'Download',
    addNotes: 'Add Notes',
    editNotes: 'Edit Notes',
    favourites: 'Favourites',
    transcript: 'Transcript',
    saveNote: 'Add Note',
    resource: 'Resources',
    episodes: 'Episodes',
    episodesRelated: 'More Like This',
    noRelated: 'No Related Videos',
    countdown: (timer: number) => `Will begin in ${timer} seconds`,
  },
  contact: {
    submit: 'Submit',
  },
  edit: {
    confirm: 'Confirm',
    save: 'Save',
  },
  home: {
    courses: 'Courses',
    creators: 'Creators',
    play: 'Play',
    nextVideo: 'Next Video',
    trendingVideos: {
      trending: 'Trending',
      category: 'Category',
      creators: 'Creators',
      tags: 'Tags',
      clearAll: 'Clear All',
    },
  },
  account: {
    usePhotoLibrary: 'Use Photo Library',
    uploadAPhoto: 'Take A Photo',
  },
  plan: {
    subscription: 'Subscription',
    transaction: 'Transaction',
  },
  assessemnt: {
    letsStart: "Let's Start",
  },
  program: {
    buildProgram: 'Build Program',
  },
  explore: {
    letsExplore: "Let's Explore",
  },
  shipping: {
    next: 'Next',
  },
  start: {
    startAssessment: 'Start Assessment',
  },
  verbal: {
    verbalCommunication: 'Verbal Communication',
    emotionalSkills: 'Emotional Skills',
    socialPlaySkills: 'Social & Play Skills',
    pottyTraining: 'Potty Training',
    sensoryNeeds: 'Sensory Needs',
  },
  visual: {
    next: 'Next',
  },
  session: {
    upcomingBookings: 'Upcoming Bookings',
    previousSession: 'Previous Sessions',
    join: 'Join Now',
    notify: 'Notify Me',
    noUpcomingSessions: 'No Upcoming Sessions Available',
    noPreviousSessions: 'No Previous Sessions Available',
    noNote: 'No notes for this session - your coach is still cooking',
    upcomingSchduleAt: 'Scheduled at',
    modal: {
      chargeBooking: 'You are going to be charged for this booking.',
      ok: 'Ok',
      cancel: 'Cancel',
    },
  },
  resource: {
    category: 'Category',
    type: 'Type',
    applyFilter: 'Apply',
    clearFilter: 'Clear All',
    explore: 'Explore',
    myCollection: 'My Collection',
    addToCollection: 'Add to Collection',
    removeToCollection: 'Remove from Collection',
    download: 'Download',
    search: 'Search',
  },
  filters: {
    category: 'Category',
    tags: 'Tags',
    creators: 'Creators',
  },
  programs: {
    inProgress: 'In Progress',
    planned: 'Planned',
    mastered: 'Mastered',
    addTask: 'Add Task',
    editTask: 'Edit Task',
    deleteTask: 'Delete Task',
    download: 'Download',
    addToCollection: 'Add to Collection',
    completeTask: 'Complete Task',
    contact: 'Contact',
  },
  profile: {
    passwordWeak: 'Password is weak',
    passwordStrong: 'Password is strong',
    firstName: 'First Name*',
    lastName: 'Last Name*',
    email: 'Email*',
    phoneNumber: 'PhoneNumber',
    password: 'Password*',
    passwordConfirm: 'Confirm Password*',
    save: 'Save',
    useCamera: 'Use Camera',
    usePhotoLibrary: 'Use Photo Library',
    cancel: 'Cancel',
  },
  profileList: {
    myProfile: 'My Profile',
    contactSupport: 'Contact Support',
    manageNotification: 'Manage Notification',
    manageSubscription: 'Manage Subscription',
    signOut: 'Sign Out',
    submodal: {
      title: 'Do you agree to update your subscription?',
      update: 'Update',
      cancel: 'Cancel',
      updatingText: "Hey, I'd like to upgrade my subscription.",
      cancelingText: "Hey, I'd like to cancel my subscription.",
    },
  },
  workshop: {
    confirm: 'Confirm',
    upcomingWorkshops: 'Upcoming Workshops',
    previousWorkshops: 'Previous Workshops',
    addToCalender: 'Add to Calender',
    notifyMe: 'Notify Me',
    okay: 'Okay',
    willNotifyBeforeWorkshop_1: 'Thanks, We will notify you',
    willNotifyBeforeWorkshop_2: 'before the Workshop!',
    featureComingSoon: 'This feature is coming soon.',
    willNotifyYou: 'We will notify you!',
    thankYou: 'Thank You',
    live: 'Live',
    noPreviousWorkshopsAvailable: 'No Previous Workshops Available',
    noUpcomingWorkshopsAvailable: 'No Upcoming Workshops Available',
    previousCard: {
      replay: 'Replay',
    },
  },
  notification: {
    today: 'Today',
    earlier: 'Earlier',
  },
  manageNotification: {
    workshopStarted: 'Notify on workshop starting',
    sessionStarted: 'Notify on session starting',
    sessionAdded: 'Notify on session note added',
    disableTitle: 'Notifications Disabled',
    disabledMessage:
      'Notifications are currently disabled,\nenable them in settings to set your\nnotification preferences.',
    settings: 'Settings',
    cancel: 'Cancel',
  },
  memberScreen: {
    title: 'Your child details',
    firstNamePlaceholder: 'First Name*',
    lastNamePlaceholder: 'Last Name*',
    genderPlaceholder: 'Gender*',
    megendaryTitle: 'First Name, Last Name, Gender',
    continueButton: 'Continue',
  },
  purchase: {
    benefits: 'BENEFITS',
    buy: 'Continue',
  },
  support: {
    title: 'Contact our support team',
  },
  errors: {
    failed: 'The sign in failed. Please try again.',
    cancelled: 'The sign in was cancelled.',
    userDisabled: 'Your account has been disabled.',
    userDetails: 'Please check your details.',
    userEmail: (email: string) => `\nYou are attempting to sign in using: ${email}`,
    login: {
      notFound: 'Please register to create an account.',
      emailNotFound: "We couldn't find an account with this email.",
      notActive: 'This account is not active.',
      notCustomer: 'Please use a customer account.',
      passwordNotMatch: 'The password is incorrect.',
    },
    email: {
      notValid: 'Email must be a valid email',
      notFound: "We couldn't find any matching details.",
      noCredential: 'Enter an email address and password',
    },
    apple: {
      noIdentity: 'No Apple identity token.',
    },
    google: {
      noIdentity: 'No Google identity token.',
      notInPlay: 'Make sure you are signed into your Google Play account.',
      playNotAvailable: 'Google Play is not available.',
    },
    connection: {
      failed: 'Please check your internet connection',
    },
    purchase: {
      failed: 'Purchase failed. You likely had a previous Subscription that you need to restore.',
    },
  },
};

export default strings;
